#include <iostream>
#include <thread>
#include <mutex>
#include <atomic>
#include <vector>
#include <string>
#include <queue>

#include <sstream> //stringstream
#include <condition_variable>
#include <future>

#include <memory>
#include <coroutine>
#include <utility> // exchange
using namespace std;




/*  => A function is a coroutine if its definition contains any of the following:
the co_await expression — to suspend execution until resumed
the co_yield expression — to suspend execution returning a value
the co_return statement — to complete execution returning a value

They come in two different forms:
■ Stackfull
■ Stackless (which is what we have in C++)

Restrictions
    1. Coroutines cannot use variadic arguments, plain return statements, or placeholder return types (auto or Concept).
        a. Variadic functions (...) rely on raw stack manipulation (va_list, va_arg), but a coroutine’s stack frame is split up and managed by the compiler.

    2. Consteval functions, constexpr functions, constructors, destructors, and the main function cannot be coroutines.

Coroutine must have either of
    - co_await
    - co_yield
    - co_return
it cannot have return statement

flags   -pthread -pcoroutine

Promise type of the Coroutine
    - Promise type is an object i.e struct or class
    - must  have the name prmise_type
    - nested within the return type ( here ReturnObject ) of the coroutine.
        struct ReturnObject {
            struct promise_type {
                // to do
            };
        };
    promise type doesn't have any rlation to std::promise

*/

struct ReturnObject {
    struct promise_type {
        promise_type() = default; /* Implicitly generated by compiler */

        std::suspend_never initial_suspend() { return {}; }
        std::suspend_never final_suspend() noexcept { return {}; }
        ReturnObject get_return_object() { return {}; }
        void unhandled_exception() {}
    };
    ReturnObject() = default; /* Implicitly generated by compiler */
};
/*  Method get_return_object: constructes ReturnObject of coroutine
        - returns the parent object of promise_type 
        - Same as return type of the coroutine
        ReturnObject get_return_object() { return {}; } her  {} represent default constructed ReturnObject

        promise_type() = default;
    A default constructor for promise_type and ReturnObject
    -   In simple cases, compiler gnerates one for user

    std::suspend_never initial_suspend() { return {}; }
        - This executed just before a core routtine starts it's execution

    void unhandled_exception() {} which for simple cases can be empty
    Used for handling uncaught exceptions in the coroutine
*/

ReturnObject foo() {
    cout << "1. hello from coroutine\n";
    // co_await std::suspend_always{};
    co_await std::suspend_never{};
    cout << "2. hello from coroutine\n";
}
void T() {
    ReturnObject retObj = foo();
}

struct ReturnObject2 {
    struct promise_type {
        // promise_type() = default; /* Implicitly generated by compiler */

        std::suspend_never initial_suspend() { return {}; }
        std::suspend_never final_suspend() noexcept { return {}; }

        ReturnObject2 get_return_object() {
            return ReturnObject2{
                // Return a ReturnObject2 that wraps a coroutine handle pointing to this promise.
                std::coroutine_handle<promise_type>::from_promise(*this)
            };
            /* std::coroutine_handle<promise_type> is a tiny object that stores a pointer to the coroutine frame.
            from_promise(*this) means:
                Take the current promise object (*this).
                Look up which coroutine frame it belongs to.
                Build a coroutine_handle that can later resume, destroy, or check status of this coroutine.*/
        }
        void unhandled_exception() {}
    };
    // ReturnObject2() = default; /* Implicitly generated by compiler */


/*  std::coroutine_handle<> is a type-erased coroutine handle.
It can point to a coroutine of any promise_type.
Think of it as void* for coroutine frames.
ReturnObject2 just stores this handle.
The constructor takes the handle from get_return_object() and saves it:
So now ReturnObject2 is the “controller” object for the coroutine.*/
    std::coroutine_handle<> handle;
    ReturnObject2(std::coroutine_handle<> handle_) : handle{handle_} {}
};
/*  How they connect together
1. Coroutine call starts (foo2())
    Compiler makes a coroutine frame with a promise_type inside.
    Calls promise.get_return_object().

2. get_return_object() runs
    Calls std::coroutine_handle<promise_type>::from_promise(*this).
    Creates a handle to the coroutine frame.
    Wraps it in a ReturnObject2.

3. ReturnObject2 constructed
    Its constructor takes the handle and stores it in handle.
    Now the caller has a handle to control the coroutine.

So in short:
    from_promise(*this) → “Get a handle to the coroutine frame that owns this promise.”
    ReturnObject2(std::coroutine_handle<> handle_) → “Store that handle so the caller can resume/destroy the coroutine.”*/

ReturnObject2 foo2() {
    cout << "1. hello from coroutine\n";
    co_await std::suspend_always{};
    // co_await std::suspend_never{};
    cout << "2. hello from coroutine\n";

    co_await std::suspend_always{};
    cout << "3. hello from coroutine\n";
}
void T2() {
    ReturnObject2 retObj2 = foo2();
    retObj2.handle.resume();
    retObj2.handle.resume();
    // retObj2.handle.resume();
    // retObj2.handle(); // Calls std::coroutine_handle<>::operator();

    // retObj2.handle();
    cout << std::boolalpha << retObj2.handle.done() << "\n";
}
// void T2() {
//     ReturnObject2 retObj2 = foo2();
//     while (!retObj2.handle.done()) {
//         retObj2.handle.resume();
//     }

//     cout << std::boolalpha << retObj2.handle.done() << "\n";  // true
// }
/*  
Compiler transformation
    When the compiler sees co_return, co_yield, or co_await, it transforms foo() into a state machine:
    Allocate a promise object (promise_type).
    Build a coroutine frame (a heap/stack object storing locals, args, and suspension state).
    Create a coroutine handle (std::coroutine_handle<promise_type>).
    Replace co_return / co_yield with calls into the promise object.


std::suspend_never for both → means:
    At the start: don’t suspend, jump straight into coroutine body.
    At the end: don’t suspend, destroy immediately.

co_await std::suspend_always{} means pause execution here until resumed.
On resume, execution continues after the suspension point.
*/





// 1.   Cannot use variadic arguments
// ReturnObject2 foo3(...) { co_await std::suspend_never(); }
ReturnObject2 foo3(auto ...args) { co_await std::suspend_never(); }

// 2.   Cannot be constexper or consteval
// constexper ReturnObject2 coro_with_constexpr() { co_await std::suspend_never{}; }

// 3.   Cannot have auto or decltype(auto) return type
auto foo4() ->ReturnObject2 { co_await std::suspend_never(); }  // Trailing Return Type
// auto with trailing return type is valid

// 4.   Cannot be constructors or destructors
struct Bar
{
    // Bar() { co_yield 5; }
    // ~Bar() { co_return std::suspend_never{}; }
};

// Cannot have plain return statement
// Use co_return to mark the end of execution


/*  Coroutine can be
A free standing coroutine
A member function of a class
A virtual function in polymorphic class
A lambda expression
A static coroutine
    Free standing
    Static member of a class
*/
// auto lambda_coro = []


// Corroutine With co_yield
struct ReturnObject3 {
    struct promise_type {
        int val_;
        std::suspend_always yield_value(int val) {
            this->val_ = val;
            return std::suspend_always{};
        }

        ReturnObject3 get_return_object() {
            return { std::coroutine_handle<promise_type>::from_promise(*this)};
        }
        std::suspend_never initial_suspend() { return {}; }
        std::suspend_always final_suspend() noexcept { return {}; }
        void unhandled_exception() {}
    };

    // You can resume(), destroy(), check if it’s done(), or access its promise() object.
    std::coroutine_handle<promise_type> handle;
    ReturnObject3(std::coroutine_handle<promise_type> h) : handle{h} { }
    operator std::coroutine_handle<promise_type>() const { return handle; }

    // Helper function to get the val_ memver within promise object
    int get_value() const { return handle.promise().val_; }
};
// co_yield 5; will call promise_type::yield_value(5);
// This value could be saved in promise object and retrive it
// frome coroutine_handle

ReturnObject3 generator(int start, int end, int steps = 1) {
    for (int val{start}; val<end; val += steps) {
        // When a coroutine uses co_yield X;, the compiler translates it into a call to promise_type::yield_value(X).
        co_yield val;
    }
}

void T3() {
    auto gen = generator(0, 10);

    int i{0};
    while(!gen.handle.done()) {
        cout << i++ << ".value: " << gen.get_value() << "\n";
        gen.handle();
    }
/*  std::coroutine_handle has an operator() overload that is equivalent to calling resume().
void operator()() const { resume(); }

So this: gen.handle();  is exactly the same as:
gen.handle.resume();*/

/*
struct MyPtr {
    int* p;
    operator int*() const { return p; }
};

MyPtr mp{new int(42)};
int* raw = mp;   // implicit conversion works
*/
    ReturnObject3 gen2 = generator(0, 5);
    std::coroutine_handle<ReturnObject3::promise_type> h = gen2.handle; // explicit
    h.resume();

}

class Chat {
// #include "promise_type.h"
public:
struct promise_type {
    std::string _msgOut{}, _msgIn{};

    void unhandled_exception() noexcept {}
    Chat get_return_object() { return Chat{this}; }
    std::suspend_always initial_suspend() noexcept { return {}; } // StartUp
    std::suspend_always yield_value(std::string msg) noexcept {   // value from co_yield
        _msgOut = std::move(msg);
        return {};
    }

    auto await_transform(std::string) noexcept {
        struct awaiter {
            promise_type &pt;
            constexpr bool await_ready() const noexcept { return true; }
            void await_suspend(std::coroutine_handle<>) const noexcept {}
            std::string await_resume() const noexcept { return pt._msgIn; }
        };
        return awaiter{*this};
    }


    void return_value(std::string msg) noexcept { _msgOut = std::move(msg); }
    std::suspend_always final_suspend() noexcept { return {}; }
};

    using Handle = std::coroutine_handle<promise_type>;
    Handle handle{};

    explicit Chat(promise_type* p) : handle{Handle::from_promise(*p)} {} // Get the handle form promis
    Chat(Chat&& rhs) : handle{std::exchange(rhs.handle, nullptr)} {} // Move only

    ~Chat() {
        if(handle) { handle.destroy(); }
    }

    std::string listen() { // Active the coroutine and wait for data
        if(not handle.done()) { handle.resume(); }
        return std::move(handle.promise()._msgOut);
    }

    void answer(std::string msg) {
        handle.promise()._msgIn = msg;
        if(not handle.done()) { handle.resume();}
    }
}; 
Chat Fun() {
    co_yield "Hello\n"s; // Call promise_type.await_value

    std::cout << co_await std::string{}; // Call promise_type.await_transform

    co_return "Here\n"s; // Call promise_type.return_value
}
void Use() {
    Chat marco = Fun();
    std::cout << marco.listen(); // Trigger the machine
    marco.answer("W r u?\n"s);
    std::cout << marco.listen();
/*Fun() is a coroutine.

co_yield "Hello\n" → suspends and returns "Hello\n" to listen().

Next time, coroutine hits std::cout << co_await std::string{} and pauses, waiting for input.

answer("W r u?\n") → stores "W r u?\n" in the promise, then resume() continues coroutine.

That co_await std::string{} pulls the stored _msgIn and sends it to std::cout.

Finally, co_return "Here\n" → returns "Here\n" to listen().*/
}
/*  get_return_object() passes a raw promise_type* (this) into the Chat constructor.

The Chat constructor is responsible for calling
std::coroutine_handle<promise_type>::from_promise(*p)
to create the coroutine handle.

So the responsibility of building the coroutine handle is pushed into the return object’s constructor.

Chat style:

promise_type only gives this to the return object.

Chat decides how to turn the promise_type* into a handle.

More flexible (return object could decide to wrap the promise differently).

ReturnObject2 style:

promise_type directly constructs the handle.

ReturnObject2 just stores what it’s given.

Simpler (less work for the return type).

========>>>>>>>>> If your return type needs more control (like Chat, which has destructor logic, move-only semantics, custom APIs like listen()/answer()), then giving it the raw promise pointer gives it maximum flexibility.*/

/*Task: A coroutine that does a job without returning a value.
Generator: A coroutine that does a job and returns a value (either by co_return or co_yield).


*/
 /*
struct suspend_always {
    constexpr bool await_ready() const noexcept {
        return false;
    }

    constexpr void
    await_suspend(std::coroutine_handle <>) const noexcept {}

    constexpr void await_resume() const noexcept {}
};

struct suspend_never {
    constexpr bool await_ready() const noexcept {
        return true;
    }

    constexpr void
    await_suspend(std::coroutine_handle <>) const noexcept {}

    constexpr void await_resume() const noexcept {}
};
*/


struct Generator {
    struct promise_type {
        int _val{};

        Generator           get_return_object() { return Generator{*this}; }
        std::suspend_never  initial_suspend() noexcept { return {}; }
        std::suspend_always final_suspend() noexcept { return {}; }
        std::suspend_always yield_value(int v) {
            _val = v;
            return {};
        }

        void return_void() noexcept {}
        void unhandled_dexeption() noexcept {}
    };
    
    using Handle = std::coroutine_handle<promise_type>;
    Handle handle;

    explicit Generator(promise_type *p) : handle{ Handle::from_promise(*p)} {}

    // Move only automatically desable copy ???
    Generator(Generator&& rhs) : handle{ std::exchange(rhs.handle, nullptr)} {}

    ~Generator () {
        if(handle) { handle.destroy(); }
    }

    int value() const { return handle. promise()._val; }

    bool finished() const { return handle.done(); }

    void resume() {
        if (not finished()) { handle.resume(); }
    }
}

Generator interleaved(std::vector<int> a, std::vector<int> b) {
    auto lamb = [](std::vector<int> &v) -> Generator {
        for (const auto&& e : v) { co_yield e; }
    };

    auto x = lamb(a);
    auto y = lamb(b);

    while ( !x.finished() | !y,finished()) {
        if (!x.finished()) {
            co_yield x.value();
            x.resume();
        }

        if (!y.finished()) {
            co_yield y.value();
            y.resume();
        }
    }
}

int main() {
    T2();
// main function Cannot be a coroutine
    T3();

    std::cout << "\n";
    Use();
}