#include <iostream>
#include <vector>
#include <climits>
#include <queue>
#include <utility>
#include <algorithm>
#include <stack>

using namespace std;

void lambda_closure_objects_SinceCPP20() {
    auto x = [](auto x) { return x+1; };
    auto y = x;
    x = y; // Assignment work since C++20

    // x and y are lambda closure objects (instances of an unnamed class 
    // generated by the compiler).
/*  It has no captures
So the closure type is stateless (empty object)

C++17 and earlier Lambda closure types were:
    Copyable (usually yes)
    BUT not necessarily assignable
    
x = y; // ERROR in pre-C++20 in many compilers
Reason: the compiler-generated closure type often had deleted assignment operators.

Since C++20 Key rule:
If a lambda closure is:
    stateless (no captures), OR has assignable members
then it becomes:
        1. CopyAssignable
        2. MoveAssignable
*/
}

void Lambdas_with_capture_ar_not_assignable() {
// What'swrong with this code?
    auto x = [m = 1](auto x) { return x+1; };
    auto y = x;
    // x = y;

    static_assert(std::is_trivially_copyable_v<decltype(x)>);

    x = y;
}

int main() {
    lambda_closure_objects_SinceCPP20();
    Lambdas_with_capture_ar_not_assignable();
    std::cout << "Success\n";
    return 0;
}